name: Push Pipeline 

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
  workflow_dispatch:

jobs:
  linting:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Run gofmt and print changes
        run: make fmt/check

      - name: Run linting check
        run: make lint

  unit_tests:
    name: unit tests (ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Run unit tests
        run: make test/unit
