name: Push Pipeline 

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
  workflow_dispatch:

jobs:
  linting:
    uses: CodeIntelligenceTesting/cifuzz/.github/workflows/resuable_linting.yml@main
  testing:
    uses: CodeIntelligenceTesting/cifuzz/.github/workflows/reusable_testing.yml@main
    with:
      integration-tests: false
      unit-tests: true
