name: Linting

on: [workflow_call]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Run gofmt and print changes
        run: make fmt/check 

      - name: Run linting check
        run: make lint
