name: Testing 

on:
  workflow_call:
    inputs:
      unit-tests:
        required: true
        type: boolean
      integration-tests:
        required: true
        type: boolean

jobs:
  unit_tests:
    if: ${{ inputs.unit-tests }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Run unit tests
        run: make test/unit

  integration_tests:
    if: ${{ inputs.integration-tests }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Run integration tests
        run: make test/integration
